### ISSUE TITLE
(view-portfolio-record) in golden cross

### ISSUE THREAD

**Issue by hkulyc** [clojure-finance/clojure-backtesting#25]
![image](https://user-images.githubusercontent.com/43634213/109387294-9254e280-793b-11eb-8a8d-1afdec7df6e6.png)
=======================
os: MAC X

**Comment by awoo424** [comment]
`view-portfolio-record` must be passed with a parameter:

- call `(view-portfolio-record -1)` to print the full record
- call `(view-portfolio-record n)` where n > 0 to print the first n rows in the record
